name: twinned
description: Boodskap Digital Twin
version: 2.0.9
publish_to: 'none'


environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  twinned_widgets:
    git:
      url: https://github.com/boodskap/twinned_widgets.git
      ref: main
#    path:
#      twinned_widgets

  twin_commons:
    git:
      url: https://github.com/boodskap/twin_commons.git
      ref: main
#    path:
#      twin_commons

  open_street_map_search_and_pick: ^0.1.1
  package_info_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  